language: python

sudo: false

python:
  - "2.7"
  - "pypy"
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - pip install coveralls --download-cache $HOME/.cache/pip
  - pip install . --download-cache $HOME/.cache/pip

script:
  - make coverage

after_success:
  - coveralls

notifications:
  email: false

cache:
  directories:
    - $HOME/.cache/pip
