language: python
python:
  - "2.7"
  - "pypy"
  - "3.3"

install:
  - pip install coveralls
  - pip install -r requirements.txt
  - python setup.py install

script:
  - coverage run --source=browsepy setup.py test

after_success:
  - coveralls

notifications:
  email: false